### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by kaniini** [writeas/writefreely#10]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55678e69dc9f]

goroutine 16687 [running]:
github.com/writeas/writefreely.handleFetchCollectionInbox.func3(0xc4203a01a8, 0xc4203a01b0, 0xc420c1f540, 0xc4203a01b8, 0xc420b46478, 0xc4201ecc90, 0xc4203a01c0, 0xc420170680, 0xc420b46479)
        /home/blog/go/src/github.com/writeas/writefreely/activitypub.go:370 +0x9bf
created by github.com/writeas/writefreely.handleFetchCollectionInbox
        /home/blog/go/src/github.com/writeas/writefreely/activitypub.go:323 +0x736
```

**Comment by thebaer** [comment]
Which commit are you on?

**Comment by thebaer** [comment]
Will reopen if we can get more information on which commit / version of the app this happened on.
