### ISSUE TITLE
not displaying blogs/posts list

### ISSUE THREAD

**Issue by severak** [writeas/writefreely#2]
I setup testing instance of WF on my windows machine. It works great. Good job!

However, when I  try to visit list my of blogs/post (as logged-in user) it throws Error 500. In webserver log there is something about null pointer dereference:

```
ERROR: 2018/11/08 13:10:56 log.go:26: runtime error: invalid memory address or n
il pointer dereference: goroutine 106 [running]:
runtime/debug.Stack(0xc042561708, 0x16086e0, 0x2439440)
        C:/Go/src/runtime/debug/stack.go:24 +0xae
github.com/writeas/writefreely.(*Handler).User.func1.1.1(0xc042386880, 0x188b8c0
, 0xc042106fc0, 0xc0424ede00, 0xc042561b70, 0xbef127d40dfb135c, 0x7adb1de9d, 0x2
44b1e0)
        C:/Users/Admin/go/src/github.com/writeas/writefreely/handle.go:83 +0x2ab

panic(0x16086e0, 0x2439440)
        C:/Go/src/runtime/panic.go:502 +0x237
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0x178edc1, 0xb, 0x0, 0x0,
 0x0)
        C:/Go/src/html/template/template.go:144 +0x4a
html/template.(*Template).ExecuteTemplate(0x0, 0x18879c0, 0xc042106fc0, 0x178edc
1, 0xb, 0x16727c0, 0xc0426d1230, 0xc042561960, 0x15)
        C:/Go/src/html/template/template.go:133 +0x4a
github.com/writeas/writefreely.showUserPage(0x188b8c0, 0xc042106fc0, 0x178edc1,
0xb, 0x16727c0, 0xc0426d1230)
        C:/Users/Admin/go/src/github.com/writeas/writefreely/templates.go:42 +0x
156
github.com/writeas/writefreely.viewCollections(0xc0421328d0, 0xc0426e2580, 0x188
b8c0, 0xc042106fc0, 0xc0424ede00, 0xc0424ede00, 0xc042561b70)
        C:/Users/Admin/go/src/github.com/writeas/writefreely/account.go:772 +0x3
99
github.com/writeas/writefreely.(*Handler).User.func1.1(0xc042386880, 0x188b8c0,
0xc042106fc0, 0xc0424ede00, 0x17e40a8, 0x0, 0x0)
        C:/Users/Admin/go/src/github.com/writeas/writefreely/handle.go:98 +0x135

github.com/writeas/writefreely.(*Handler).User.func1(0x188b8c0, 0xc042106fc0, 0x
c0424ede00)
        C:/Users/Admin/go/src/github.com/writeas/writefreely/handle.go:108 +0x61

net/http.HandlerFunc.ServeHTTP(0xc0423873c0, 0x188b8c0, 0xc042106fc0, 0xc0424ede
00)
        C:/Go/src/net/http/server.go:1947 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc04217d3b0, 0x188b8c0, 0xc042106fc0
, 0xc0424ede00)
        C:/Users/Admin/go/src/github.com/gorilla/mux/mux.go:162 +0xf4
net/http.(*ServeMux).ServeHTTP(0x244ad20, 0x188b8c0, 0xc042106fc0, 0xc0424ed600)

        C:/Go/src/net/http/server.go:2337 +0x137
net/http.serverHandler.ServeHTTP(0xc0422a85b0, 0x188b8c0, 0xc042106fc0, 0xc0424e
d600)
        C:/Go/src/net/http/server.go:2694 +0xc3
net/http.(*conn).serve(0xc0423e79a0, 0x188bc40, 0xc0423aa940)
        C:/Go/src/net/http/server.go:1830 +0x658
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2795 +0x282
```

**Comment by thebaer** [comment]
Thanks, glad it's working! :smile: 

What's your app configuration? If it's set to be a single-user instance, that might be what's causing this, as that mode is incomplete right now. All those kinks should be worked out today -- but let me know if you're using a different config.

**Comment by severak** [comment]
my config is this:

```
[app]
site_name         = Kyselo 2.0
host              = http://localhost:8008
theme             = write
disable_js        = false
webfonts          = true
single_user       = false
open_registration = true
min_username_len  = 3
max_blogs         = 3
federation        = false
public_stats      = false
private           = false
```

(ommited database part)

**Comment by thebaer** [comment]
Thanks. Couldn't verify this, but my hunch is that it's caused by bad template paths on Windows. I'll be pushing up a fix soon.
