### ISSUE TITLE
AP actors have erroneous sharedInbox

### ISSUE THREAD

**Issue by kaniini** [writeas/writefreely#8]
In my actor, https://blog.dereferenced.org/api/collections/kaniini, I see:

```
"endpoints":{"sharedInbox":""}
```

This is obviously wrong ;)

**Comment by kaniini** [comment]
if you must have it due to go structs being the way they are it should be set to `null`.

**Comment by thebaer** [comment]
Gotcha. Besides this issue, a shared inbox isn't needed, right? But it's probably a good thing to have?

**Comment by kaniini** [comment]
In your case, it is probably not necessary.

**Comment by kaniini** [comment]
Looks like adding `omitempty` to `sharedInbox` in web-core/data.go should fix this.

**Comment by thebaer** [comment]
Yep. Should an empty `endpoints` property be left out, too?

**Comment by kaniini** [comment]
Ideally yes, but it doesn't matter.  In LitePub, `sharedInbox` would generally be preferred if it is set, but Pleroma should also guard against that invalid value :)

However, there's another problem, your Accepts are wrong:

```
16:50:14.945 [info] Unhandled activity
16:50:14.950 [info] {
  "type": "Accept",
  "object": {
    "type": "Follow",
    "to": "https://blog.dereferenced.org/api/collections/kaniini",
    "state": "pending",
    "published": "2018-11-11T16:50:12Z",
    "object": "https://blog.dereferenced.org/api/collections/kaniini",
    "id": "https://pleroma.site/activities/b5bb0ad7-72fa-46d6-bc44-ced092bc3436",
    "context_id": 15104353,
    "context": "https://pleroma.site/contexts/1b428def-c9b3-4a4b-9f6e-465c84701b02",
    "cc": "https://www.w3.org/ns/activitystreams#Public",
    "actor": "https://pleroma.site/users/kaniini"
  },
  "nickname": "kaniini",
  "cc": [
    "https://pleroma.site/users/kaniini"
  ],
  "actor": "https://blog.dereferenced.org/api/collections/kaniini",
  "@context": [
    "https://www.w3.org/ns/activitystreams"
  ]
}
```

They need to be addressed `to` me, not `cc` me.

**Comment by kaniini** [comment]
Also

```
ERROR: 2018/11/11 16:50:14 log.go:26: Couldn't add new remoteuser in DB: Error 1364: Field 'followers' doesn't have a default value
```

Going to guess you need to do something with SQL there.

**Comment by kaniini** [comment]
oh, I see.  nevermind on the `to`/`cc`.  it's something else that Pleroma is hating.

**Comment by kaniini** [comment]
aha, the issue is that you're not generating an `id` for the accept.

**Comment by thebaer** [comment]
Ah ok, I'll get that in there.

Also that `followers` column shouldn't be in there -- it's a leftover from my local environment. This will fix that:

```
ALTER TABLE `remoteusers` DROP `followers`;
```

**Comment by kaniini** [comment]
Alright, I did that, and that got rid of that error, but publishing a blog post does not result in the blog post being distributed to subscribers.

**Comment by kaniini** [comment]
Ah, I see, it is only published directly if and only if I directly publish it there (instead of promoting a draft).

However...

```
17:16:11.027 [error] Task #PID<0.5979.0> started from Pleroma.Web.Federator terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Stream
    (elixir) /home/buildozer/aports/community/elixir/src/elixir-1.6.5/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /home/buildozer/aports/community/elixir/src/elixir-1.6.5/lib/elixir/lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:1919: Enum.uniq_by/2
    (pleroma) lib/pleroma/web/activity_pub/utils.ex:525: Pleroma.Web.ActivityPub.Utils.make_create_data/2
    (pleroma) lib/pleroma/web/activity_pub/activity_pub.ex:124: Pleroma.Web.ActivityPub.ActivityPub.create/1
    (pleroma) lib/pleroma/web/federator/federator.ex:106: Pleroma.Web.Federator.handle/2
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<12.33571476/0 in Pleroma.Web.Federator.maybe_start_job/2>
    Args: []
```

This is because your `Create` activity does not have `actor` set.

**Comment by thebaer** [comment]
Yeah, [still need to send activities](https://phabricator.write.as/T526) around moving posts from draft to a blog or between blogs.

But are you sure the `Create` activity doesn't have an `actor`? It should be getting set to the activity [here](https://github.com/writeas/web-core/blob/master/activitystreams/activity.go#L45), with the `AttributedTo` field set [here](https://github.com/writeas/writefreely/blob/master/posts.go#L1037)

**Comment by kaniini** [comment]
Yeah, actually your `Create` is fine.  Sorry about that.  Digging a bit.

**Comment by kaniini** [comment]
Aha.  I see the problem.  Your `Create` is not addressed, only the underlying object is.

**Comment by thebaer** [comment]
So you need to be able to directly access the `Create` activity at its own URL / `id`?

**Comment by kaniini** [comment]
I did this:

```
diff --git a/activitypub.go b/activitypub.go
index 60561af..5a27ca2 100644
--- a/activitypub.go
+++ b/activitypub.go
@@ -580,6 +580,8 @@ func federatePost(app *app, p *PublicPost, collID int64, isUpdate bool) error {
                        activity = activitystreams.NewUpdateActivity(na)
                } else {
                        activity = activitystreams.NewCreateActivity(na)
+                       activity.To = na.To
+                       activity.CC = na.CC
                }
                err = makeActivityPost(actor, si, activity)
                if err != nil {
```

and that works.

**Comment by kaniini** [comment]
by the way, `Update` support is going to be a doozy.  nobody has successfully implemented it yet :)

**Comment by thebaer** [comment]
Oh, got it. Will add that.

But yeah, just wanted to be future-proof by including `Update`s. [Read.as](https://github.com/writeas/Read.as) does implement it and it seems to work, at least in our little universe of implementations :)

**Comment by kaniini** [comment]
The problem isn't with processing the literal `Update`, it's with preventing scenarios like:

* Molly posts a photo of her cat.  People are boosting it like crazy.
* Few hours later, Molly `Update`s her cat photo to be nazi imagery.

Meaning that `Announce`s need to become versioned, etc.

**Comment by kaniini** [comment]
Looks like other than the activities having to/cc on them (just copy them from the object, but you don't really need them on the object, just the activities themselves) and the Accepts not having an `id`, everything seems pretty solid here.  At least solid enough that I can use it for my blog.

**Comment by thebaer** [comment]
> Meaning that `Announce`s need to become versioned, etc.

Ah, makes sense. Yeah that'll definitely be interesting!

For everything else, I've just pushed up their fixes. Just tested with Pleroma and it seems to work great!
